# Generated by Django 5.2.3 on 2025-09-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="gradient_end",
            field=models.CharField(
                default="#4caf50",
                help_text="Couleur hexadécimale pour le bas du dégradé (ex. #4caf50).",
                max_length=7,
                verbose_name="Gradient end color",
            ),
        ),
        migrations.AddField(
            model_name="siteconfiguration",
            name="gradient_start",
            field=models.CharField(
                default="#2f6ee2",
                help_text="Couleur hexadécimale pour le haut du dégradé (ex. #2f6ee2).",
                max_length=7,
                verbose_name="Gradient start color",
            ),
        ),
    ]
