# Generated by Django 5.2.3 on 2025-07-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AvailableYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Year")),
                (
                    "type",
                    models.CharField(
                        choices=[("budget", "Budget"), ("actual", "Comptes")],
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name": "Available year",
                "verbose_name_plural": "Available years",
                "ordering": ("-year",),
                "unique_together": {("year", "type")},
            },
        ),
    ]
