# Generated by Django 5.2.3 on 2026-09-03 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_availableyear_scheme"),
    ]

    operations = [
        migrations.CreateModel(
            name="SankeyCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "flow",
                    models.CharField(
                        choices=[
                            ("revenue", "Revenue"),
                            ("canton", "Canton"),
                            ("intercommunality", "Intercommunality"),
                            ("commune", "Commune"),
                            ("dotation", "Dotation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("color", models.CharField(max_length=7)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Sankey category",
                "verbose_name_plural": "Sankey categories",
                "ordering": ("flow", "order"),
            },
        ),
        migrations.CreateModel(
            name="SankeyLabelRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "scheme",
                    models.CharField(
                        choices=[("mch1", "MCH1"), ("mch2", "MCH2")], max_length=10
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        help_text="Case-insensitive substring match.",
                        max_length=100,
                        verbose_name="Label contains",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="label_rules",
                        to="finance.sankeycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sankey label rule",
                "verbose_name_plural": "Sankey label rules",
                "ordering": ("scheme", "pattern"),
            },
        ),
        migrations.CreateModel(
            name="SankeyNatureRangeRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "scheme",
                    models.CharField(
                        choices=[("mch1", "MCH1"), ("mch2", "MCH2")], max_length=10
                    ),
                ),
                (
                    "nature_start",
                    models.PositiveIntegerField(verbose_name="From nature"),
                ),
                ("nature_end", models.PositiveIntegerField(verbose_name="To nature")),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nature_range_rules",
                        to="finance.sankeycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sankey nature range rule",
                "verbose_name_plural": "Sankey nature range rules",
                "ordering": ("scheme", "priority", "nature_start"),
            },
        ),
        migrations.CreateModel(
            name="SankeyAccountCodeRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "scheme",
                    models.CharField(
                        choices=[("mch1", "MCH1"), ("mch2", "MCH2")], max_length=10
                    ),
                ),
                ("function", models.CharField(max_length=10, verbose_name="Function")),
                ("nature", models.CharField(max_length=10, verbose_name="Nature")),
                (
                    "sub_account",
                    models.CharField(
                        blank=True,
                        help_text="Leave blank to match any subaccount under this function/nature.",
                        max_length=10,
                        verbose_name="Subaccount",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_code_rules",
                        to="finance.sankeycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sankey account code rule",
                "verbose_name_plural": "Sankey account code rules",
                "ordering": ("scheme", "function", "nature"),
                "unique_together": {("scheme", "function", "nature", "sub_account")},
            },
        ),
    ]
