# Generated by Django 5.2.3 on 2026-09-04 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_refine_mch2_nature_ranges"),
    ]

    operations = [
        migrations.CreateModel(
            name="SankeyFunctionNatureRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "scheme",
                    models.CharField(
                        choices=[("mch1", "MCH1"), ("mch2", "MCH2")], max_length=10
                    ),
                ),
                (
                    "function_prefix",
                    models.CharField(max_length=10, verbose_name="Function prefix"),
                ),
                (
                    "nature_start",
                    models.PositiveIntegerField(verbose_name="From nature"),
                ),
                ("nature_end", models.PositiveIntegerField(verbose_name="To nature")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="function_nature_rules",
                        to="finance.sankeycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sankey function/nature rule",
                "verbose_name_plural": "Sankey function/nature rules",
                "ordering": ("scheme", "function_prefix", "nature_start"),
            },
        ),
    ]
