# Generated by Django 5.2.3 on 2026-09-04 12:23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_add_autres_commune_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sankeycategory",
            name="color",
            field=models.CharField(max_length=7, verbose_name="Color"),
        ),
        migrations.AlterField(
            model_name="sankeycategory",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="sankeycategory",
            name="order",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Order"),
        ),
        migrations.AlterField(
            model_name="sankeynaturerangerule",
            name="priority",
            field=models.PositiveSmallIntegerField(
                default=100, verbose_name="Priority"
            ),
        ),
    ]
