# Generated by Django 5.2.3 on 2025-07-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_authorizedemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_municipal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="trigram",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
