# Generated by Django 5.2.3 on 2025-07-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_is_municipal_user_trigram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="trigram",
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
