# Generated by Django 5.2.3 on 2026-09-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_trigram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="trigram",
            field=models.CharField(blank=True, max_length=3, verbose_name="Trigram"),
        ),
    ]
