# Generated by Django 5.2.17 on 2026-09-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_trigram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "This email has already been taken."},
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
