# Generated by Django 5.2.17 on 2026-09-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_municipal",
            field=models.BooleanField(default=False, verbose_name="Municipal officer"),
        ),
    ]
