# Generated by Django 5.2.3 on 2025-07-08 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bdi_import", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountimportlog",
            old_name="csv_path",
            new_name="file_path",
        ),
    ]
