# Generated by Django 5.2.3 on 2025-07-31 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdi_import", "0002_rename_csv_path_accountimportlog_file_path"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountimportlog",
            name="file_path",
        ),
        migrations.AddField(
            model_name="accountimportlog",
            name="copy_comments",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="accountimportlog",
            name="copy_labels",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="accountimportlog",
            name="copy_responsibles",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="accountimportlog",
            name="copy_visibility",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="accountimportlog",
            name="file",
            field=models.FileField(default="", upload_to="imports/accounts/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="accountimportlog",
            name="source_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finance.availableyear",
            ),
        ),
    ]
