# Generated by Django 5.2.3 on 2025-07-31 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdi_import", "0003_remove_accountimportlog_file_path_and_more"),
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountimportlog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Account import log",
                "verbose_name_plural": "Account import logs",
            },
        ),
        migrations.AlterField(
            model_name="accountimportlog",
            name="copy_comments",
            field=models.BooleanField(default=True, verbose_name="Copy comments"),
        ),
        migrations.AlterField(
            model_name="accountimportlog",
            name="copy_labels",
            field=models.BooleanField(default=True, verbose_name="Copy labels"),
        ),
        migrations.AlterField(
            model_name="accountimportlog",
            name="copy_responsibles",
            field=models.BooleanField(default=True, verbose_name="Copy responsibles"),
        ),
        migrations.AlterField(
            model_name="accountimportlog",
            name="copy_visibility",
            field=models.BooleanField(default=True, verbose_name="Copy visibility"),
        ),
        migrations.AlterField(
            model_name="accountimportlog",
            name="dry_run",
            field=models.BooleanField(default=False, verbose_name="Dry run"),
        ),
        migrations.AlterField(
            model_name="accountimportlog",
            name="file",
            field=models.FileField(
                upload_to="imports/accounts/", verbose_name="Import file"
            ),
        ),
        migrations.AlterField(
            model_name="accountimportlog",
            name="is_budget",
            field=models.BooleanField(verbose_name="Is budget"),
        ),
        migrations.AlterField(
            model_name="accountimportlog",
            name="launched_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Launched by",
            ),
        ),
        migrations.AlterField(
            model_name="accountimportlog",
            name="message",
            field=models.TextField(blank=True, verbose_name="Message"),
        ),
        migrations.AlterField(
            model_name="accountimportlog",
            name="source_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="finance.availableyear",
                verbose_name="Source year",
            ),
        ),
        migrations.AlterField(
            model_name="accountimportlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("started", "Started"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="accountimportlog",
            name="year",
            field=models.PositiveIntegerField(verbose_name="Year"),
        ),
    ]
