# Generated by Django 5.2.3 on 2025-08-02 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdi_import", "0004_alter_accountimportlog_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColumnMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("code", "Account code"),
                            ("label", "Account label"),
                            ("charges", "Charges"),
                            ("revenues", "Revenues"),
                            ("total", "Total (signed)"),
                        ],
                        max_length=20,
                        verbose_name="Mapped field",
                    ),
                ),
                (
                    "column_name",
                    models.CharField(max_length=100, verbose_name="Excel column name"),
                ),
                (
                    "derived_from_total",
                    models.BooleanField(
                        default=False,
                        help_text="Use positive/negative values from 'total' column to infer charges/revenues.",
                        verbose_name="Derived from total column",
                    ),
                ),
                (
                    "log",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="column_mappings",
                        to="bdi_import.accountimportlog",
                        verbose_name="Import log",
                    ),
                ),
            ],
            options={
                "verbose_name": "Column mapping",
                "verbose_name_plural": "Column mappings",
                "unique_together": {("log", "field")},
            },
        ),
    ]
