# Generated by Django 5.2.3 on 2025-09-17 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bdi_import", "0005_columnmapping"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="columnmapping",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Column mapping",
                "verbose_name_plural": "Column mappings",
            },
        ),
        migrations.AddField(
            model_name="columnmapping",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="columnmapping",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
