# Generated by Django 5.2.3 on 2026-09-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bdi_import",
            "0006_alter_columnmapping_options_columnmapping_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="accountimportlog",
            name="kind",
            field=models.CharField(
                choices=[("bdi", "BDI export"), ("excel", "Manual Excel")],
                default="bdi",
                max_length=10,
                verbose_name="Kind",
            ),
        ),
        migrations.AddField(
            model_name="accountimportlog",
            name="scheme",
            field=models.CharField(
                choices=[("mch1", "MCH1"), ("mch2", "MCH2")],
                default="mch1",
                max_length=10,
                verbose_name="Scheme",
            ),
        ),
        migrations.AlterField(
            model_name="columnmapping",
            name="field",
            field=models.CharField(
                choices=[
                    ("code", "Account code"),
                    ("function", "Function"),
                    ("nature", "Nature"),
                    ("sub_account", "Sub account"),
                    ("label", "Account label"),
                    ("charges", "Charges"),
                    ("revenues", "Revenues"),
                    ("total", "Total (signed)"),
                    ("responsible", "Responsible (trigram)"),
                ],
                max_length=20,
                verbose_name="Mapped field",
            ),
        ),
    ]
