# Generated by Django 5.2.3 on 2025-07-08 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("year", models.PositiveIntegerField(db_index=True)),
                ("function", models.SmallIntegerField(db_index=True)),
                ("nature", models.SmallIntegerField(db_index=True)),
                ("sub_account", models.SmallIntegerField(blank=True, null=True)),
                ("label", models.CharField(max_length=255)),
                ("is_budget", models.BooleanField(default=False)),
                ("charges", models.DecimalField(decimal_places=2, max_digits=15)),
                ("revenues", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "expected_type",
                    models.CharField(
                        choices=[
                            ("charges", "Charges only"),
                            ("revenues", "Revenues only"),
                            ("both", "Both charges and revenues"),
                        ],
                        default="charges",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ("year", "nature", "function", "nature", "sub_account"),
            },
        ),
        migrations.CreateModel(
            name="AccountGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=3, unique=True)),
                ("label", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccountComment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("content", models.TextField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="accounting.account",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounting.accountgroup",
            ),
        ),
        migrations.CreateModel(
            name="GroupResponsibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("municipal_name", models.CharField(max_length=100)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responsibilities",
                        to="accounting.accountgroup",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["year", "function"], name="accounting__year_3809bc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["year", "nature"], name="accounting__year_1782e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="account",
            index=models.Index(
                fields=["function", "nature", "sub_account"],
                name="accounting__functio_434ca7_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together={
                ("year", "function", "nature", "sub_account", "is_budget")
            },
        ),
        migrations.AlterUniqueTogether(
            name="groupresponsibility",
            unique_together={("group", "year")},
        ),
    ]
