# Generated by Django 5.2.3 on 2025-07-08 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_supergroup_alter_account_group_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accountgroup",
            options={"ordering": ("code",)},
        ),
        migrations.AlterModelOptions(
            name="supergroup",
            options={"ordering": ("code",)},
        ),
        migrations.AlterField(
            model_name="accountgroup",
            name="code",
            field=models.SmallIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name="accountgroup",
            name="supergroup",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="accounting.supergroup",
            ),
        ),
        migrations.AlterField(
            model_name="supergroup",
            name="code",
            field=models.SmallIntegerField(db_index=True, unique=True),
        ),
    ]
