# Generated by Django 5.2.3 on 2025-07-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0003_alter_accountgroup_options_alter_supergroup_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MetaGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.SmallIntegerField(db_index=True, unique=True)),
                ("label", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ("code",),
            },
        ),
    ]
