# Generated by Django 5.2.3 on 2025-07-25 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_metagroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="supergroup",
            name="metagroup",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supergroups",
                to="accounting.metagroup",
            ),
        ),
    ]
