# Generated by Django 5.2.3 on 2025-07-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0005_supergroup_metagroup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupresponsibility",
            options={
                "verbose_name": "Responsable",
                "verbose_name_plural": "Responsables",
            },
        ),
        migrations.RemoveField(
            model_name="groupresponsibility",
            name="municipal_name",
        ),
    ]
