# Generated by Django 5.2.3 on 2025-07-25 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_alter_groupresponsibility_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupresponsibility",
            options={
                "ordering": ("group__code", "year"),
                "verbose_name": "Responsable",
                "verbose_name_plural": "Responsables",
            },
        ),
    ]
