# Generated by Django 5.2.3 on 2025-07-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0007_alter_groupresponsibility_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountgroup",
            name="code",
            field=models.CharField(db_index=True, max_length=5, unique=True),
        ),
    ]
