# Generated by Django 5.2.3 on 2025-07-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0008_alter_accountgroup_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "ordering": ("year", "nature", "function", "nature", "sub_account"),
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
            },
        ),
        migrations.AlterModelOptions(
            name="accountcomment",
            options={
                "ordering": (
                    "account__year",
                    "account__nature",
                    "account__function",
                    "created_at",
                ),
                "verbose_name": "Account Comment",
                "verbose_name_plural": "Account Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="accountgroup",
            options={
                "ordering": ("code",),
                "verbose_name": "Account Group",
                "verbose_name_plural": "Account Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="groupresponsibility",
            options={
                "ordering": ("group__code", "year"),
                "verbose_name": "Responsible",
                "verbose_name_plural": "Responsibles",
            },
        ),
        migrations.AlterModelOptions(
            name="metagroup",
            options={
                "ordering": ("code",),
                "verbose_name": "Meta Group",
                "verbose_name_plural": "Meta Groups",
            },
        ),
        migrations.AlterModelOptions(
            name="supergroup",
            options={
                "ordering": ("code",),
                "verbose_name": "Super Group",
                "verbose_name_plural": "Super Groups",
            },
        ),
        migrations.AddField(
            model_name="account",
            name="visible_in_report",
            field=models.BooleanField(default=True),
        ),
    ]
