# Generated by Django 5.2.3 on 2025-07-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0009_alter_account_options_alter_accountcomment_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="function",
            field=models.CharField(db_index=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="nature",
            field=models.CharField(db_index=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="sub_account",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="visible_in_report",
            field=models.BooleanField(verbose_name=True),
        ),
    ]
