# Generated by Django 5.2.3 on 2025-07-29 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0010_alter_account_function_alter_account_nature_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "ordering": ("function", "nature", "sub_account", "year"),
                "verbose_name": "Account",
                "verbose_name_plural": "Accounts",
            },
        ),
        migrations.AlterField(
            model_name="account",
            name="charges",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Charges"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="expected_type",
            field=models.CharField(
                choices=[
                    ("charges", "Charges only"),
                    ("revenues", "Revenues only"),
                    ("both", "Both charges and revenues"),
                ],
                default="charges",
                max_length=10,
                verbose_name="Expected type",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="function",
            field=models.CharField(db_index=True, verbose_name="Function"),
        ),
        migrations.AlterField(
            model_name="account",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="accounting.accountgroup",
                verbose_name="Group",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="label",
            field=models.CharField(max_length=255, verbose_name="Label"),
        ),
        migrations.AlterField(
            model_name="account",
            name="nature",
            field=models.CharField(db_index=True, verbose_name="Nature"),
        ),
        migrations.AlterField(
            model_name="account",
            name="revenues",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Revenues"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="sub_account",
            field=models.CharField(blank=True, null=True, verbose_name="Subaccount"),
        ),
        migrations.AlterField(
            model_name="account",
            name="visible_in_report",
            field=models.BooleanField(default=True, verbose_name="Visible in report"),
        ),
        migrations.AlterField(
            model_name="account",
            name="year",
            field=models.PositiveIntegerField(db_index=True, verbose_name="Year"),
        ),
    ]
