# Generated by Django 5.2.3 on 2025-07-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0011_alter_account_options_alter_account_charges_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="sub_account",
            field=models.CharField(blank=True, default="", verbose_name="Subaccount"),
            preserve_default=False,
        ),
    ]
