# Generated by Django 5.2.3 on 2026-09-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0015_remove_metagroup_supergroup"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountCodeMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("mch1_function", models.CharField(verbose_name="MCH1 function")),
                ("mch1_nature", models.CharField(verbose_name="MCH1 nature")),
                (
                    "mch1_sub_account",
                    models.CharField(blank=True, verbose_name="MCH1 subaccount"),
                ),
                ("mch2_function", models.CharField(verbose_name="MCH2 function")),
                ("mch2_nature", models.CharField(verbose_name="MCH2 nature")),
                (
                    "mch2_sub_account",
                    models.CharField(blank=True, verbose_name="MCH2 subaccount"),
                ),
            ],
            options={
                "verbose_name": "Account code mapping",
                "verbose_name_plural": "Account code mappings",
                "ordering": ("mch2_function", "mch2_nature", "mch2_sub_account"),
                "unique_together": {
                    (
                        "mch1_function",
                        "mch1_nature",
                        "mch1_sub_account",
                        "mch2_function",
                        "mch2_nature",
                        "mch2_sub_account",
                    )
                },
            },
        ),
    ]
