# Generated by Django 5.2.3 on 2026-09-02 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0016_accountcodemapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="NatureGroup",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(db_index=True, max_length=5)),
                ("label", models.CharField(max_length=150)),
                (
                    "scheme",
                    models.CharField(
                        choices=[("mch1", "MCH1"), ("mch2", "MCH2")],
                        default="mch2",
                        max_length=10,
                    ),
                ),
                ("level", models.PositiveSmallIntegerField()),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="accounting.naturegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nature Group",
                "verbose_name_plural": "Nature Groups",
                "ordering": ("scheme", "level", "code"),
                "unique_together": {("scheme", "level", "code")},
            },
        ),
    ]
