# Generated by Django 5.2.17 on 2026-09-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0017_naturegroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountcomment",
            name="content",
            field=models.TextField(verbose_name="Content"),
        ),
    ]
