# Generated by Django 5.2.17 on 2026-09-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0018_alter_accountcomment_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupresponsibility",
            options={
                "ordering": ("group__code", "function", "year"),
                "verbose_name": "Responsible",
                "verbose_name_plural": "Responsibles",
            },
        ),
        migrations.AlterUniqueTogether(
            name="groupresponsibility",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="groupresponsibility",
            name="function",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Function"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="groupresponsibility",
            unique_together={("group", "function", "year")},
        ),
    ]
